#!/bin/tcsh

if ($4 == "") then
  if ( $3 == "" ) then
    if ( $2 == "" ) then
  	swipl << %
  	[foodweb1].
  	$1.
  
  X is cputime, write(X), write(' seconds').
%
    else
  	swipl << %
  	[$1].
	$2.
  
  X is cputime, write(X), write(' seconds').
%
    endif
  else
#  	swipl << %
#  	[yap_metagol_d].
#  	learn_seq([$1,$2,$3],[],[],B).
  
  X is cputime, write(X), write(' seconds').
%
  endif
else
#	swipl << %
#	[yap_metagol_d].
#	learn_seq([$1,$2,$3,$4],[],[],B).

X is cputime, write(X), write(' seconds').
%
endif
